version: '3.4'

services:
  emotions-recognition:
    image: emotions-recognition
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 train.py
    volumes:
      - .:/app/train
